name: "example_for_generator"
description: example
version: 0.0.1
homepage: https://github.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_asset_generator:
    path: ../.

flutter:
  assets:
    - images/
    - assets/
